feature to exclude certain parts of all DOM with querySelector.
arkon/ng-click-outside pull request #5
Opened 2016-10-31 20:27 UTC by JulioWar

Is like feature of outside-if-not in  @iamadamjowett/angular-click-outside repository

2016-10-31 23:22 UTC, arkon requested changes
Thanks a lot for the PR! I've added a few comments, but they should be easy to take care of. :)

2016-10-31 23:22 UTC, arkon commented on src/click-outside.directive.ts
> +        let nodeExcluded = this.exclude.split(',');
Might be better to call this something else. I was mixing up this with the class's instance of `nodeExcluded` for a bit.

2016-10-31 23:22 UTC, arkon commented on src/click-outside.directive.ts
> +    Directive,
Could we stick with 2 spaces for the indentation?

2016-10-31 23:22 UTC, arkon commented on src/click-outside.directive.ts
> +    ngOnChanges(changes: SimpleChanges) {
Might need to handle the case where `exclude` is updated as well.

2016-10-31 23:22 UTC, arkon commented on src/click-outside.directive.ts
> +        this.nodeExcluded.forEach((node) => {
Might be better to just use a regular forloop so we can prematurely break out of it when `flag` gets set to `true`. The `return` will only break off the one iteration but still continue on for the rest.

2016-10-31 23:32 UTC, JulioWar commented
Ok, thanks for take a time to review my code, i going to see the comments and fix them.

2016-11-16 17:52 UTC, JulioWar commented
@arkon i made the changes. see the commit.
Let me know if I have to change anything.

2016-11-16 18:38 UTC, arkon commented
@JulioWar There appear to be merge conflicts.

2016-11-16 23:33 UTC, JulioWar commented
@arkon but, how can i solve it? 
i dont know where exactly the conflict is and i dont have the write access to do the merge.

2016-11-17 01:26 UTC, arkon commented
Check out this article: https://help.github.com/articles/syncing-a-fork/

2016-11-17 01:40 UTC, merged

2016-11-17 01:41 UTC, JulioWar commented
Thanks for the article 👍

2016-11-17 01:50 UTC, arkon commented
@JulioWar Thanks for the contribution! I've published v1.3.0 with it.

2016-11-17 01:56 UTC, JulioWar commented
@arkon Your welcome, I learned how to make a pull request 😄

2016-12-15 13:17 UTC, centigrade-thomas-becker commented
Can somebody please add some example on how to use exclude? What exactly is a DOM element query?

2016-12-15 15:54 UTC, JulioWar commented
Hello @centigrade-thomas-becker 

You can use exclude feature like `querySelector` in pure javascript. Check [querySelector Documentation](http://www.w3schools.com/jsref/met_document_queryselector.asp). 

You need to put the element as a string, like this:
```
[exclude]="'button,.btn-primary'"
```

2016-12-15 16:42 UTC, arkon commented
@JulioWar I added that example to the README, but it also got me wondering if it should be `querySelectorAll` in the code instead?

2016-12-15 17:02 UTC, JulioWar commented
Yes @arkon, I agree, we can use `querySelectorAll` to get all nodes instead of use a loop

2016-12-15 17:19 UTC, arkon commented
@JulioWar I made the change. It'll be included in the next release.